# Generated by Django 5.1.4 on 2024-12-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='frames/%d-%m-%Y/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
