# Generated by Django 5.1.4 on 2024-12-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoanal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
    ]
